--SCOTT접속 
SELECT * FROM emp;
SELECT * FROM dept; --부서정보
SELECT * FROM salgrade; --급여등급

DESC DEPT
-- 1. SMITH 에 대한  정보 검색(ename, emp.deptno, loc .)
SELECT ENAME, EMP.DEPTNO, LOC
FROM EMP ,DEPT 
WHERE EMP.DEPTNO = DEPT.DEPTNO AND EMP.ENAME= 'SMITH';


SELECT ENAME, DEPTNO, LOC
FROM EMP JOIN DEPT
USING (DEPTNO)
WHERE ENAME='SMITH';


--2. NEW YORK에 근무하는 사원의 이름과 급여를 출력

SELECT ENAME , SAL
FROM EMP ,DEPT 
WHERE EMP.DEPTNO = DEPT.DEPTNO AND DEPT.LOC='NEW YORK';

SELECT ENAME ,SAL
FROM EMP JOIN DEPT
USING(DEPTNO)
WHERE LOC='NEW YORK';

-- 3. ACCOUNTING 부서 소속 사원의 이름과 입사일 출력

SELECT ENAME , SAL
FROM EMP ,DEPT 
WHERE EMP.DEPTNO = DEPT.DEPTNO AND DEPT.DNAME='ACCOUNTING';

SELECT ENAME , SAL
FROM EMP JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO AND DEPT.DNAME='ACCOUNTING';


-- 4. 직급이 MANAGER인 사원의 이름, 부서명 출력

SELECT E.ENAME,D.DNAME
FROM EMP E,DEPT D
WHERE E.DEPTNO = D.DEPTNO AND E.JOB='MANAGER';

SELECT ENAME,DNAME
FROM EMP JOIN DEPT
USING (DEPTNO)
WHERE  DEPTNO = DEPTNO AND JOB='MANAGER';


-- 5. 사원의 급여가 몇 등급인지를 검색
-- between A and B
select * from salgrade;
select * from emp;

SELECT ENAME, GRADE
FROM EMP JOIN SALGRADE
ON SAL BETWEEN LOSAL AND HISAL;  


SELECT EMPNO, ENAME, SAL, GRADE, LOSAL, HISAL
 FROM EMP JOIN salgrade
 ON SAL BETWEEN LOSAL AND HISAL;
 


--6. 사원 테이블의 부서 번호로 부서 테이블을 참조해서 부서명, 급여 등급도 검색
SELECT EMP.ENAME, DEPT.DNAME , GRADE
FROM EMP JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO JOIN SALGRADE
ON SAL BETWEEN LOSAL AND HISAL;



SELECT ENAME , DNAME,GRADE
FROM EMP JOIN DEPT
USING(DEPTNO) JOIN SALGRADE
ON SAL BETWEEN LOSAL AND HISAL;


SELECT * FROM emp;
SELECT * FROM dept; --부서정보
SELECT * FROM salgrade; --급여등급
--7. SMITH의 메니저(mgr) 이름(ename) 검색

SELECT E1.ENAME ||'의 매니저 이름은 '|| E2.ENAME ||'입니다'
FROM EMP E1 LEFT JOIN EMP E2
ON E1.MGR = E2.EMPNO
WHERE E1.ENAME ='SMITH';

--8. 관리자가 KING인 사원들의 이름과 직급(job) 검색

SELECT *FROM EMP
WHERE MGR = (SELECT EMPNO FROM EMP WHERE ENAME ='KING');

SELECT E1.ENAME,E1.JOB,E2.ENAME
FROM EMP E1 JOIN EMP E2
ON E1.MGR = E2.EMPNO AND E2.ENAME= 'KING';

--9. SMITH 와 동일한 부서번호(DEPTNO)에서 근무하는 사원의 이름 출력
-- 단, SMITH 데이터 절대 출력 불가

SELECT E1.ENAME,E2.ENAME
FROM EMP E1 JOIN EMP E2
ON E1.DEPTNO = E2.DEPTNO WHERE E1.ENAME='SMITH' AND E2.ENAME != 'SMITH';

--10. SMITH 와 동일한 근무지(LOC)에서 근무하는 사원의 이름 출력
-- 단, SMITH 데이터 절대 출력 불가

SELECT * FROM emp;
SELECT * FROM dept; --부서정보
SELECT * FROM salgrade; --급여등급

SELECT * FROM EMP JOIN DEPT USING(DEPTNO)
JOIN
SELECT * FROM EMP JOIN DEPT USING(DEPTNO);


SELECT D1.ENAME ,D1.LOC, D2.ENAME , D2.LOC
FROM (SELECT * FROM EMP JOIN DEPT USING(DEPTNO)) D1 JOIN (SELECT * FROM EMP JOIN DEPT USING(DEPTNO)) D2 
ON D1.LOC = D2.LOC
WHERE D1.ENAME='SMITH' AND D2.ENAME !='SMITH';




-- 11, 사원명, 해당 하는 메니저명 검색
-- 반드시 모든 사원들(CEO포함) 정보 검색
-- CEO인 경우 메니저 정보 null

SELECT E1.ENAME 사원이름 , E2.ENAME 관리자이름
FROM EMP E1 LEFT JOIN EMP E2
ON E1.MGR = E2.EMPNO;

SELECT * FROM emp;
SELECT * FROM dept; --부서정보
SELECT * FROM salgrade; --급여등급










