CREATE TABLE SUBJECT(
    SUBJECT_CODE VARCHAR2(5) PRIMARY KEY,
    SUBJECT VARCHAR2(20) NOT NULL
);

CREATE TABLE ROOM(
    ROOM_NUMBER NUMBER PRIMARY KEY,
    ROOM_PERSONNEL NUMBER NOT NULL
);

CREATE TABLE TEACHER(
    THACHER_NUMBER NUMBER PRIMARY KEY,
    TEACHER_NAME VARCHAR2(14) NOT NULL,
    TEACHER_PHONE VARCHAR2(14) NOT NULL,
    TEACHER_ADDR VARCHAR2(50),
    TEACHER_EMAIL VARCHAR2(20),
    SUBJECT_CODE VARCHAR2(5) NOT NULL CONSTRAINT SUBJCET_CODE_FK  REFERENCES SUBJECT(SUBJECT_CODE)

);

CREATE TABLE STUDENT(
    STUDENT_NUMBER NUMBER PRIMARY KEY,
    STUDENT_NAME VARCHAR2(12) NOT NULL,
    STUDENT_JUMIN VARCHAR2(14) NOT NULL,
    STUDENT_PHONE VARCHAR2(14) NOT NULL,
    STUDENT_ADDR VARCHAR2(50),
    STUDENT_EMAIL VARCHAR2(20)

);

CREATE TABLE SUGAGN(
    STUDENT_NUMBER NUMBER PRIMARY KEY  CONSTRAINT STUDENT_NUMBER_FK REFERENCES STUDENT(STUDENT_NUMBER),
    SUBJECT_CODE VARCHAR2(5) CONSTRAINT SUBJECT_CODE_FK REFERENCES SUBJECT(SUBJECT_CODE)

);




























